### ISSUE TITLE
Cannot go install tesla-keygen

### ISSUE THREAD

**Issue by andig** [teslamotors/vehicle-command#181]
```
go install github.com/teslamotors/vehicle-command/cmd/tesla-keygen@latest
go: github.com/teslamotors/vehicle-command/cmd/tesla-keygen@latest (in github.com/teslamotors/vehicle-command@v0.0.2):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

using Go 1.21

**Comment by sethterashima** [comment]
The work around, which I know is less than satisfactory, is to clone the repository and `go install ./...`.

Unfortunately, fixing the issue doesn't seem feasible given the restrictions on `go install`. The underlying issue is that the OSX BLE Go package that all the cross-platform Go BLE packages rely on is no longer maintained but [has a bug](https://github.com/JuulLabs-OSS/cbgo/pull/3) that prevents it from working with BLE devices that use 32-bit UUIDs. As a result, our go.mod file points at a fork that has this bug fixed. But `go install` doesn't work with `go.mod` files that use redirect to forks.

There are plenty of prolonged discussion threads on this problem, but, as far as I can tell, no clean solutions. Happy to be corrected on this if someone knows of one.
