### ISSUE TITLE
Account wiped from Fleet API after fleet-telemetry CSR setup: "Account [client-id] must be registered in the current region"

### ISSUE THREAD

**Issue by stx** [teslamotors/vehicle-command#195]
After Tesla completed our fleet-telemetry CSR setup today (not sure if it's related, but it's the only thing happening that I'm aware of), our whole account became unregistered from Fleet API at 4:30PM PST:

HTTP Error Code 412
{"error":"Account [client-id] must be registered in the current region https://fleet-api.prd.na.vn.cloud.tesla.com/, please see https://developer.tesla.com/docs/fleet-api#register"}

We have changed nothing on our end, so no idea what's going on here. The client ID shows up as Active on the developer dashboard at https://developer.tesla.com/dashboard/app-details/[client_id].

update:

We fixed this by manually reregistering with each region following the instructions at https://developer.tesla.com/docs/fleet-api#register. No idea why it randomly (?) vanished from Fleet API.

**Comment by jbanyer** [comment]
FWIW we (chargehq.net) are not seeing this error. Most of our vehicles are in the NA region.

**Comment by stx** [comment]
Okay, so after Tesla completed our fleet-telemetry CSR setup today, the whole account became unregistered from the Fleet API regions.

We fixed this by manually reregistering with each region following the instructions at https://developer.tesla.com/docs/fleet-api#register.

FYI for everyone else that runs into this.

**Comment by jbanyer** [comment]
I had this happen with our test domain `tesla.chqtest.net`. It occurred many days after Tesla approved the CSR, so that doesn't appear to be the cause.

When it happened, the following changes had been made:
- our public key had been taken down temporarily for about 24 hours
- we enabled fleet telemetry on a vehicle for the first time

So I'm not sure what triggered the issue. Perhaps the public key being taken down?

The fix was to re-register the public key again.
