### ISSUE TITLE
Registering app with car fails with "Request timed out"

### ISSUE THREAD

**Issue by rawmean** [teslamotors/vehicle-command#211]
Some users are getting this message from Tesla app when they try to register my 3rd party app with the car:
<img width="630" alt="image" src="https://github.com/teslamotors/vehicle-command/assets/1287087/e72244b0-04d4-4092-9c1d-159748df0b53">

**Comment by sethterashima** [comment]
Request timeouts can be caused by a variety of issues, most of them transient and caused by factors outside Tesla's control.  If you're able to reliably reproduce in a setting where the mobile phone has connectivity to both Tesla's servers and the vehicle, please follow the instructions under [Fleet API Help And Support](https://developer.tesla.com/docs/fleet-api#help-and-support).
