### ISSUE TITLE
Are you able to get a public key using localhost:<port number> as your domain?

### ISSUE THREAD

**Issue by nbosio1001** [teslamotors/vehicle-command#218]
I am trying to setup my public key to my .well-known folder and am trying to use for the partner register and public_key endpoints. May I do this without having to host a website; adding more complications to running my program?

**Comment by sethterashima** [comment]
The intention here is that 3rd party apps are identified by their domain name. When the user approves the example.com app, their phone fetches the public key from example.com and adds it to the vehicle keychain. Since the last step isn't possible with a localhost domain, registering an app with localhost isn't possible. (Tesla also checks the public key is valid at registration time; clearly this also isn't possible from localhost).

If your app just exclusively uses BLE, you shouldn't need to register at all.

If you don't want to purchase a domain name, you could look into using a free dynamic DNS provider (though you'd still need to run a webserver on your pi or similar during registration).

We hope to add better support for self-hosted applications down the road, but for now those are your options.
