### ISSUE TITLE
403 on Vehicles from fleet account?

### ISSUE THREAD

**Issue by vbarrier** [teslamotors/vehicle-command#252]
Hi, now on most of our vehicles we have this error:

`403 - "{\"error\":\"Tesla Vehicle Command Protocol required, please refer to the documentation here: https://developer.tesla.com/docs/fleet-api#2023-10-09-rest-api-vehicle-commands-endpoint-deprecation-warning\",\"error_description\":\"\",\"response\":null}"`

Theses cars are owned by a fleet account  (T4B right?) with several drivers assigned. From the documentation it says that cars in fleet accounts are excluded: "*Fleet accounts are excluded from these changes until further notice. Pre-2021 Model S/X are excluded from these changes."

Why I can't send remote commands anymore? 

(This is blocker as the car is rented without a way to physically access it)

Thanks!

**Comment by sethterashima** [comment]
Please contact Fleet API support: https://developer.tesla.com/docs/fleet-api#help-and-support. If it's a backend configuration issue, then they should be able to resolve it. They may also be able to suggest alternatives if you can provide more context to the problem you're facing.

However, once vehicles switch to the new protocol, Tesla can't remotely switch them back; this is required to get the security benefits of end-to-end authentication. If you are able to regain physical access, then performing a factory reset directly from the UI will in most cases cause the vehicle to revert to the older protocol. Make sure you've confirmed the vehicle is on a fleet account first, otherwise it will automatically switch back.

**Comment by vbarrier** [comment]
Thank you!
