### ISSUE TITLE
Updating to latest golang?

### ISSUE THREAD

**Issue by oderby** [teslamotors/vehicle-command#297]
Go 1.23 was [released last week](https://go.dev/doc/devel/release), which means the version of go currently used here, 1.20, is no longer receiving security fixes and minor releases. What is the process for updating to the version of go? Would you be open to the community submitting a PR with the upgrade? And thoughts/preferences on upgrading one major release at a time vs jumping to latest? Thanks!

**Comment by patrickdemers6** [comment]
Updating to the latest version would be a great contribution.

> What is the process for updating to the version of go?

Upgrading Go is usually just a matter of updating `go.mod` and running `go mod tidy`. If any documentation references the go version, be sure to update that as well.

> And thoughts/preferences on upgrading one major release at a time vs jumping to latest?

This should be relatively low risk since Go aims to never break existing code within `1.x` releases. [More details here](https://tip.golang.org/doc/go1compat). I would say it's fine to upgrade directly.

If you plan to do this, let me know and I'll assign you this ticket.
